export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  meeting: '/meeting',
  meetings: '/meetings',
  meetingDetail: '/meetings/:id',
  settings: '/settings',
  uiLab: '/ui-lab',
  onboarding: '/onboarding',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  organizations: '/organizations',
  orgSettings: '/org/settings',
  orgKnowledge: '/org/knowledge',
  orgDocuments: '/org/documents',
  orgTasks: '/org/tasks',
  orgTaskDetail: '/org/tasks/:taskId',
  profile: '/profile',
  orgMembers: '/org/members',
  orgMemberProfile: '/org/members/:userId',
  orgWebhooks: '/org/webhooks',
  orgEmail: '/org/email',
  orgIntegrations: '/org/integrations',
  productSales: '/products/sales',
  productCustomerSupport: '/products/customer-support',
  pricing: '/pricing',
  demoSite: '/demo',
  resources: '/resources',
  blog: '/blog',
  blogPost: '/blog/:slug',
  privacy: '/privacy',
  terms: '/terms',
  cookies: '/cookies',
  acceptableUse: '/acceptable-use',
  security: '/security',
  // Admin dashboard
  admin: '/admin',
  adminUsers: '/admin/users',
  adminUserDetail: '/admin/users/:id',
  adminOrganizations: '/admin/organizations',
  adminOrgDetail: '/admin/organizations/:id',
  adminEmail: '/admin/email',
  adminManagement: '/admin/admins',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
