export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  meeting: '/meeting',
  meetings: '/meetings',
  meetingDetail: '/meetings/:id',
  settings: '/settings',
  uiLab: '/ui-lab',
  onboarding: '/onboarding',
  verifyEmail: '/verify-email',
  organizations: '/organizations',
  orgSettings: '/org/settings',
  orgKnowledge: '/org/knowledge',
  orgDocuments: '/org/documents',
  orgTasks: '/org/tasks',
  orgTaskDetail: '/org/tasks/:taskId',
  profile: '/profile',
  orgMembers: '/org/members',
  orgMemberProfile: '/org/members/:userId',
  orgWebhooks: '/org/webhooks',
  orgEmail: '/org/email',
  orgIntegrations: '/org/integrations',
  orgInterviews: '/org/roles',
  orgInterviewRole: '/org/roles/:roleSlug',
  orgInterviewCreate: '/org/roles/new',
  orgInterviewEdit: '/org/interviews/:interviewId/edit',
  orgInterviewDetail: '/org/interviews/:interviewId',
  productSales: '/products/sales',
  productInterviews: '/products/interviews',
  productCustomerSupport: '/products/customer-support',
  resources: '/resources',
  blog: '/blog',
  blogPost: '/blog/:slug',
  privacy: '/privacy',
  terms: '/terms',
  cookies: '/cookies',
  acceptableUse: '/acceptable-use',
  security: '/security',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
